### ISSUE TITLE
missing units in all colorbars

### ISSUE THREAD

**Issue by kuchaale** [VACILT/SSW_project#18]
We need to define units in the [`sea` function](https://github.com/VACILT/SSW_project/blob/7980042e61c5820fca9b2aaf14b787b78a64204e/definitions.py#L76) in the following way: 
```python
comp_m.attrs['units'] = var.attrs['units']
```
so that xarray handles them in the colorbar label.

**Comment by kuchaale** [comment]
Another modification below:
```python
temp = ds['u0'].attrs
comp_m.attrs['units'] = list(temp.values())[0].split(' / ')[-1]
```

**Comment by kuchaale** [comment]
I cannot see any change in [definitions.py](https://github.com/VACILT/SSW_project/blob/master/definitions.py). Did you commit it?

**Comment by gast-ben** [comment]
> 
> 
> I cannot see any change in [definitions.py](https://github.com/VACILT/SSW_project/blob/master/definitions.py). Did you commit it?

Yeah, I forgot to commit the new version. I've done it just now.
