### ISSUE TITLE
Analyse new files from various aspects

### ISSUE THREAD

**Issue by kuchaale** [VACILT/SSW_project#2]
Analyse new files (`/gemeinsam_tmp/UA_students/data/PW_GW_analysis`) from various aspects:

- [x] repeat previous composite analysis without final warmings only using `wind/u0`and `wind/v0`
   - [x] Add CMOR plots
- [x] focus on PW energy (`waves/PW`)
- [x] focus on GW energy (`waves/GW`)

**Comment by kuchaale** [comment]
Looking at [Issue_6_Examine_individual_events_RioGrande.ipynb](https://github.com/VACILT/SSW_project/blob/master/Issue_6_Examine_individual_events_RioGrande.ipynb), it seems that 2010 and 2013 SSWs are duplicated here because of different dates in Denton and King's studies. I would use dates from King's study since it is consistent with other papers (e.g. [Butler et al, 2017](https://www.earth-syst-sci-data.net/9/63/2017/)). @gast-ben, please revise it. [McCormack et al, 2021](https://acp.copernicus.org/preprints/acp-2021-224/) use even a different date for the 2010 event though. We would really need to do own classification for #4.

**Comment by gast-ben** [comment]
> 
> 
> Looking at [Issue_6_Examine_individual_events_RioGrande.ipynb](https://github.com/VACILT/SSW_project/blob/master/Issue_6_Examine_individual_events_RioGrande.ipynb), it seems that 2010 and 2013 SSWs are duplicated here because of different dates in Denton and King's studies. I would use dates from King's study since it is consistent with other papers (e.g. [Butler et al, 2017](https://www.earth-syst-sci-data.net/9/63/2017/)). @gast-ben, please revise it. [McCormack et al, 2021](https://acp.copernicus.org/preprints/acp-2021-224/) use even a different date for the 2010 event though. We would really need to do own classification for #4.

That's right. 2010 and 2013 SSWs are duplicated. Was revised. Only problem is, that now we have few events only - especially at RioGrande (4 SSW events).

**Comment by kuchaale** [comment]
Can you @gast-ben 

- [ ] change "Wave measurements" rather to "Wave estimates"
- [ ] add `hide-input` tag in all notebooks (see #9)

?
