### ISSUE TITLE
How to scale logarithmic color scale?

### ISSUE THREAD

**Issue by kuchaale** [VACILT/SSW_project#25]
Specifying `vmin` and `vmax` may solve our issue:
```python
norm=colors.LogNorm()
da.plot.contourf(norm = norm, vmin = 1, vmax = 1000, levels = 21, extend = 'both')
```
or consider switching to [ProPlot](https://proplot.readthedocs.io/en/latest/2dplots.html#Colormaps-and-normalizers).

**Comment by gast-ben** [comment]
vmin and vmax specification worked out.
