### ISSUE TITLE
Role of terdiurnal tide in GW energy composite

### ISSUE THREAD

**Issue by kuchaale** [VACILT/SSW_project#3]
Produce composite of terdiurnal tide and look how much variance in GW energy can be attributed to it. Related to #2. Use "old" files (`/gemeinsam_tmp/UA_students/data/`).

**Comment by kuchaale** [comment]
All updated files where terdiunal tide is excluded from GW activity can be found here: `/gemeinsam_tmp/UA_students/data/PW_GW_analysis/t_tide_sa`.

**Comment by gast-ben** [comment]
No difference is to be seen between GW activity from files with terdiurnal tide included and from files without the tides - neither for the stations on NH nor those on SH.  [https://github.com/VACILT/SSW_project/commit/1543c6403a95c06306c916d18cb010aea353975b](url)

**Comment by kuchaale** [comment]
Are you sure @gast-ben? I checked the climatology and the difference is apparent:
## with terdiurnal tide
![image](https://user-images.githubusercontent.com/6815953/129236567-3e0245b2-b103-4479-b97a-031c01a85bcd.png)
## without terdiurnal tide
![image](https://user-images.githubusercontent.com/6815953/129236741-1d61665e-6b8a-40a8-8968-2d09438da1f5.png)

**Comment by gast-ben** [comment]
GW residuals with and without the tides for each station are displayed directly underneath each other on the website.
