### ISSUE TITLE
Examine individual events

### ISSUE THREAD

**Issue by kuchaale** [VACILT/SSW_project#6]
Examine individual events to examine periodicities in GWs and PWs. We could already see quasi 2-day wave before a central data in Rio Grande. Related to #2.

**Comment by kuchaale** [comment]
The 2-day structure in zonal wind anomalies was not that apparent as in the case of hourly data (see [Issue 2 - Analysis of new data.ipynb](https://github.com/VACILT/SSW_project/blob/master/Issue%202%20-%20Analysis%20of%20new%20data.ipynb)).

**Comment by kuchaale** [comment]
Plotting would be nice with [pydata/xarray#4378](https://github.com/pydata/xarray/issues/4378).

**Comment by kuchaale** [comment]
@gast-ben,  you can perform wavelet analyses using [PyCWT](https://pycwt.readthedocs.io/en/latest/tutorial.html).

**Comment by kuchaale** [comment]
Also, examine an increased GW activity in around 100 km 40-60 days after SSW onset before on the SH.

**Comment by gast-ben** [comment]
Enhanced GW activity only appears for one SSW event each (2010 for Rio and 2013 for Davis)

**Comment by gast-ben** [comment]
The quasi-two-day-fluctuations in the meridional wind component at Rio Grande only appeared in the 2010 event analysis around 3 to 1 week before the SSW onset.

The strongly increased PW activity arround the SSW onset was only apparent for half of the SSW events at Rio Grande (2 out of 4).
